# Generated by Django 4.2.23 on 2025-10-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(default="10.208.3.153", max_length=50)),
            ],
        ),
    ]
