# Generated by Django 4.2.23 on 2025-10-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0002_cameraip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cameraip",
            name="ip_address",
        ),
        migrations.AddField(
            model_name="cameraip",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cameraip",
            name="url",
            field=models.URLField(default="http://10.208.3.153:8080"),
        ),
    ]
