# Generated by Django 4.2.23 on 2025-10-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0003_remove_cameraip_ip_address_cameraip_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameraip",
            name="url",
            field=models.CharField(max_length=255),
        ),
    ]
