# Generated by Django 4.2.23 on 2025-10-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0004_alter_cameraip_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cameraip",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="cameraip",
            name="url",
        ),
        migrations.AddField(
            model_name="cameraip",
            name="ip_address",
            field=models.CharField(default="http://10.249.11.206:8080", max_length=50),
        ),
    ]
