# Generated by Django 4.2.23 on 2025-10-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0005_remove_cameraip_updated_at_remove_cameraip_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameraip",
            name="ip_address",
            field=models.CharField(default="http://10.249.11.206:8080", max_length=100),
        ),
    ]
